[project]
name = "to-do-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyfiglet>=1.0.4",
    "textual>=6.11.0",
    "textual-dev>=1.8.0",
]
